[default_versions]
bun_version = "1.3.11"
php_version = "8.5.4"
postgresql_version = "16.2"

[installations]
bun_install = true
vue_install = true
laravel_install = true
php_install = true
postgresql_install = true