[project]
name = "project"
edition = "1.0"

[stack]
frontend = "vue"
backend = "laravel"
database = "mysql"

[ports]
php_port = 8080
laravel_port = 8081
mysql_port = 8082
vue_port = 8083

[paths]
backend_dir = "./backend"
frontend_dir = "./frontend"

[versions]
bun_version = "1.3.6"
vue_version = "3.5.31"
laravel_version = "13"
php_version = "8.5.4"
mysql_version = "8.0.46"

[mysql]
db = "my_database"
host = "localhost"
user = "root"
pass = "admin"
