[ports]
php_port = 8080
laravel_port = 8081
mysql_port = 8082
vue_port = 8083

[paths]
backend_dir = "./backend"
frontend_dir = "./frontend"

[mysql]
db = "my_database"
host = "localhost"
user = "root"
pass = "admin"
